sankey-beta
    Total Budget, EC2, 8.19
    Total Budget, RDS, 1.26
    Total Budget, Data Transfer, 0.55
    Total Budget, Waste, 1.00
    
    EC2, Optimized EC2, 1.45
    EC2, Savings, 6.74
    
    RDS, Optimized RDS, 0.24
    RDS, Savings, 1.02
    
    Waste, Savings, 1.00
